wip
> @elizaos/agent@0.1.7-alpha.2 start /mnt/data1/nix/time/2024/12/31/cloud-deployment-eliza/agent
> node --trace-event-categories node,node.bootstrap,node.console,node.vm.script,v8,node.http,node.net.native,node.environment,node.fs.sync,node.fs_dir.sync,node.fs.async,node.fs_dir.async   --loader ts-node/esm src/index.ts "--isRoot" "--characters=characters/eliza.character.json"

(node:4172648) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("ts-node/esm", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4172648) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
file:///mnt/data1/nix/time/2024/12/31/cloud-deployment-eliza/packages/core/dist/index.js:12
    throw Error('Dynamic require of "' + x + '" is not supported');
          ^

Error: Dynamic require of "path" is not supported
    at file:///mnt/data1/nix/time/2024/12/31/cloud-deployment-eliza/packages/core/dist/index.js:12:11
    at ../../node_modules/require-in-the-middle/index.js (file:///mnt/data1/nix/time/2024/12/31/cloud-deployment-eliza/packages/core/dist/index.js:4381:21)
    at __require2 (file:///mnt/data1/nix/time/2024/12/31/cloud-deployment-eliza/packages/core/dist/index.js:18:52)
    at ../../node_modules/@opentelemetry/instrumentation/build/esm/platform/node/RequireInTheMiddleSingleton.js (file:///mnt/data1/nix/time/2024/12/31/cloud-deployment-eliza/packages/core/dist/index.js:4786:48)
    at __init (file:///mnt/data1/nix/time/2024/12/31/cloud-deployment-eliza/packages/core/dist/index.js:15:58)
    at ../../node_modules/@opentelemetry/instrumentation/build/esm/platform/node/instrumentation.js (file:///mnt/data1/nix/time/2024/12/31/cloud-deployment-eliza/packages/core/dist/index.js:5218:9)
    at __init (file:///mnt/data1/nix/time/2024/12/31/cloud-deployment-eliza/packages/core/dist/index.js:15:58)
    at ../../node_modules/@opentelemetry/instrumentation/build/esm/platform/node/index.js (file:///mnt/data1/nix/time/2024/12/31/cloud-deployment-eliza/packages/core/dist/index.js:5591:9)
    at __init (file:///mnt/data1/nix/time/2024/12/31/cloud-deployment-eliza/packages/core/dist/index.js:15:58)
    at ../../node_modules/@opentelemetry/instrumentation/build/esm/platform/index.js (file:///mnt/data1/nix/time/2024/12/31/cloud-deployment-eliza/packages/core/dist/index.js:5598:9)

Node.js v23.5.0
/mnt/data1/nix/time/2024/12/31/cloud-deployment-eliza/agent:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @elizaos/agent@0.1.7-alpha.2 start: `node --trace-event-categories node,node.bootstrap,node.console,node.vm.script,v8,node.http,node.net.native,node.environment,node.fs.sync,node.fs_dir.sync,node.fs.async,node.fs_dir.async   --loader ts-node/esm src/index.ts "--isRoot" "--characters=characters/eliza.character.json"`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
Failed to start project.